import { createHash } from 'node:crypto';
import type { Plugin } from 'vite';
import { defineConfig } from 'vitest/config';

/**
 * Offline play (R-1008): writes sw.js into the build with the list of every built file, so the
 * service worker can fetch them all when it installs. The cache is named for the list's hash;
 * a new build makes a new cache and the old one is dropped.
 */
function serviceWorker(): Plugin {
  return {
    name: 'new-world-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const files = ['./', 'manifest.webmanifest', 'icon.svg', ...Object.keys(bundle).filter((name) => name !== 'sw.js')].sort();
      const version = createHash('sha256').update(files.join('\n')).digest('hex').slice(0, 12);
      const source = `// Generated by vite.config.ts. Serves the game from a cache so it can be played offline.
const CACHE = 'new-world-${version}';
const FILES = ${JSON.stringify(files)};
// the page asks for its scripts with CORS headers the worker's own fetch did not send: match on the address alone
const MATCH = { ignoreSearch: true, ignoreVary: true };
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((names) => Promise.all(names.filter((n) => n.startsWith('new-world-') && n !== CACHE).map((n) => caches.delete(n)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  // the page itself: the network first, so a new version is picked up; the cache when offline
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match('./', MATCH).then((hit) => hit ?? Response.error())));
    return;
  }
  // everything else is named by its contents: the cache first
  event.respondWith(caches.match(request, MATCH).then((hit) => hit ?? fetch(request)));
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

export default defineConfig({
  base: './',
  plugins: [serviceWorker()],
  test: {
    include: ['test/unit/**/*.test.ts', 'test/sim/**/*.test.ts'],
    environment: 'node',
  },
});
